package com.zf.live.dao.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{buyrecored}
 * by is_zhoufeng@163.com 2014-12-15 17:32:50
 */
public class Buyrecored implements Serializable {
    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 用户id  
     * column{userid},jdbcType{BIGINT}
     */
    private Long userid;

    /**
     * 商品id  
     * column{goodsid},jdbcType{BIGINT}
     */
    private Long goodsid;

    /**
     * 商品名称  
     * column{goodsname},jdbcType{VARCHAR}
     */
    private String goodsname;

    /**
     * 话费钢镚  
     * column{costcoin},jdbcType{BIGINT}
     */
    private Long costcoin;

    /**
     * 消费时间  
     * column{createtime},jdbcType{TIMESTAMP}
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buyrecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户id  
     * column{userid},jdbcType{BIGINT}
     */
    public Long getUserid() {
        return userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * 商品id  
     * column{goodsid},jdbcType{BIGINT}
     */
    public Long getGoodsid() {
        return goodsid;
    }

    public void setGoodsid(Long goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * 商品名称  
     * column{goodsname},jdbcType{VARCHAR}
     */
    public String getGoodsname() {
        return goodsname;
    }

    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    /**
     * 话费钢镚  
     * column{costcoin},jdbcType{BIGINT}
     */
    public Long getCostcoin() {
        return costcoin;
    }

    public void setCostcoin(Long costcoin) {
        this.costcoin = costcoin;
    }

    /**
     * 消费时间  
     * column{createtime},jdbcType{TIMESTAMP}
     */
    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}