package com.zf.live.dao.pojo;

import java.io.Serializable;

/**
 * tableName{goods}
 * by is_zhoufeng@163.com 2014-12-15 17:32:50
 */
public class Goods implements Serializable {
    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 商品名称  
     * column{name},jdbcType{VARCHAR}
     */
    private String name;

    /**
     * 数量  
     * column{quantity},jdbcType{BIGINT}
     */
    private Long quantity;

    /**
     * 单位  
     * column{unit},jdbcType{VARCHAR}
     */
    private String unit;

    /**
     * 价钱(需要花费的钢镚数量）  
     * column{coin},jdbcType{BIGINT}
     */
    private Long coin;

    /**
     * 商品描述  
     * column{desc},jdbcType{VARCHAR}
     */
    private String desc;

    /**
     * 商品分类  
     * column{classify},jdbcType{TINYINT}
     */
    private Byte classify;

    /**
     * 是否删除，0：未删除，1：已删除  
     * column{isdelete},jdbcType{TINYINT}
     */
    private Byte isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 商品名称  
     * column{name},jdbcType{VARCHAR}
     */
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * 数量  
     * column{quantity},jdbcType{BIGINT}
     */
    public Long getQuantity() {
        return quantity;
    }

    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * 单位  
     * column{unit},jdbcType{VARCHAR}
     */
    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * 价钱(需要花费的钢镚数量）  
     * column{coin},jdbcType{BIGINT}
     */
    public Long getCoin() {
        return coin;
    }

    public void setCoin(Long coin) {
        this.coin = coin;
    }

    /**
     * 商品描述  
     * column{desc},jdbcType{VARCHAR}
     */
    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * 商品分类  
     * column{classify},jdbcType{TINYINT}
     */
    public Byte getClassify() {
        return classify;
    }

    public void setClassify(Byte classify) {
        this.classify = classify;
    }

    /**
     * 是否删除，0：未删除，1：已删除  
     * column{isdelete},jdbcType{TINYINT}
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }
}