package com.zf.live.dao.pojo;

import java.io.Serializable;

/**
 * tableName{lvuser}
 * by is_zhoufeng@163.com 2014-12-14 06:42:10
 */
public class Lvuser implements Serializable {
    /**
     *   
     * column{id},jdbcType{INTEGER}
     */
    private Integer id;

    /**
     * 用户名  
     * column{username},jdbcType{VARCHAR}
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lvuser
     *
     * @mbggenerated Sun Dec 14 06:42:10 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{id},jdbcType{INTEGER}
     */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 用户名  
     * column{username},jdbcType{VARCHAR}
     */
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}