package com.zf.live.dao.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{playrecored}
 * by is_zhoufeng@163.com 2014-12-15 17:32:50
 */
public class Playrecored implements Serializable {
    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 用户id  
     * column{userid},jdbcType{BIGINT}
     */
    private Long userid;

    /**
     * 靓号（冗余）  
     * column{idxcode},jdbcType{VARCHAR}
     */
    private String idxcode;

    /**
     * 昵称（冗余）  
     * column{usernick},jdbcType{VARCHAR}
     */
    private String usernick;

    /**
     * 视频ID  
     * column{videoid},jdbcType{BIGINT}
     */
    private Long videoid;

    /**
     * 视频名称  
     * column{videoname},jdbcType{VARCHAR}
     */
    private String videoname;

    /**
     * 赞数  
     * column{praise},jdbcType{BIGINT}
     */
    private Long praise;

    /**
     * 开始时间  
     * column{starttime},jdbcType{TIMESTAMP}
     */
    private Date starttime;

    /**
     * 结束时间  
     * column{endtime},jdbcType{TIMESTAMP}
     */
    private Date endtime;

    /**
     * 播放秒数（endtime - starttime）  
     * column{playseconds},jdbcType{BIGINT}
     */
    private Long playseconds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table playrecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户id  
     * column{userid},jdbcType{BIGINT}
     */
    public Long getUserid() {
        return userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * 靓号（冗余）  
     * column{idxcode},jdbcType{VARCHAR}
     */
    public String getIdxcode() {
        return idxcode;
    }

    public void setIdxcode(String idxcode) {
        this.idxcode = idxcode;
    }

    /**
     * 昵称（冗余）  
     * column{usernick},jdbcType{VARCHAR}
     */
    public String getUsernick() {
        return usernick;
    }

    public void setUsernick(String usernick) {
        this.usernick = usernick;
    }

    /**
     * 视频ID  
     * column{videoid},jdbcType{BIGINT}
     */
    public Long getVideoid() {
        return videoid;
    }

    public void setVideoid(Long videoid) {
        this.videoid = videoid;
    }

    /**
     * 视频名称  
     * column{videoname},jdbcType{VARCHAR}
     */
    public String getVideoname() {
        return videoname;
    }

    public void setVideoname(String videoname) {
        this.videoname = videoname;
    }

    /**
     * 赞数  
     * column{praise},jdbcType{BIGINT}
     */
    public Long getPraise() {
        return praise;
    }

    public void setPraise(Long praise) {
        this.praise = praise;
    }

    /**
     * 开始时间  
     * column{starttime},jdbcType{TIMESTAMP}
     */
    public Date getStarttime() {
        return starttime;
    }

    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * 结束时间  
     * column{endtime},jdbcType{TIMESTAMP}
     */
    public Date getEndtime() {
        return endtime;
    }

    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * 播放秒数（endtime - starttime）  
     * column{playseconds},jdbcType{BIGINT}
     */
    public Long getPlayseconds() {
        return playseconds;
    }

    public void setPlayseconds(Long playseconds) {
        this.playseconds = playseconds;
    }
}