package com.zf.live.dao.pojo;

import java.io.Serializable;

/**
 * tableName{roomsetting}
 * by is_zhoufeng@163.com 2014-12-15 17:32:50
 */
public class Roomsetting implements Serializable {
    /**
     * 对应userid  
     * column{id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 登录名（冗余）  
     * column{loginname},jdbcType{VARCHAR}
     */
    private String loginname;

    /**
     * 房间背景图片地址（相对路径）  
     * column{backgrondimg},jdbcType{VARCHAR}
     */
    private String backgrondimg;

    /**
     * 房间名  
     * column{roomname},jdbcType{VARCHAR}
     */
    private String roomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table roomsetting
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * 对应userid  
     * column{id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 登录名（冗余）  
     * column{loginname},jdbcType{VARCHAR}
     */
    public String getLoginname() {
        return loginname;
    }

    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    /**
     * 房间背景图片地址（相对路径）  
     * column{backgrondimg},jdbcType{VARCHAR}
     */
    public String getBackgrondimg() {
        return backgrondimg;
    }

    public void setBackgrondimg(String backgrondimg) {
        this.backgrondimg = backgrondimg;
    }

    /**
     * 房间名  
     * column{roomname},jdbcType{VARCHAR}
     */
    public String getRoomname() {
        return roomname;
    }

    public void setRoomname(String roomname) {
        this.roomname = roomname;
    }
}