package com.zf.live.dao.pojo;

import java.io.Serializable;

/**
 * tableName{roomsetting}
 * by is_zhoufeng@163.com 2014-12-14 06:42:10
 */
public class Roomsetting implements Serializable {
    /**
     *   
     * column{id},jdbcType{INTEGER}
     */
    private Integer id;

    /**
     *   
     * column{roonname},jdbcType{VARCHAR}
     */
    private String roonname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table roomsetting
     *
     * @mbggenerated Sun Dec 14 06:42:10 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{id},jdbcType{INTEGER}
     */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *   
     * column{roonname},jdbcType{VARCHAR}
     */
    public String getRoonname() {
        return roonname;
    }

    public void setRoonname(String roonname) {
        this.roonname = roonname;
    }
}