package com.zf.live.dao.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{thirduser}
 * by is_zhoufeng@163.com 2015-01-01 16:38:01
 */
public class Thirduser implements Serializable {
    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 用户id  
     * column{userid},jdbcType{BIGINT}
     */
    private Long userid;

    /**
     * 用户来源，1：QQ ， 2：SINA  
     * column{userfrom},jdbcType{TINYINT}
     */
    private Byte userfrom;

    /**
     * 第三方平台的id  
     * column{openid},jdbcType{VARCHAR}
     */
    private String openid;

    /**
     * 关联时间  
     * column{createtime},jdbcType{TIMESTAMP}
     */
    private Date createtime;

    /**
     * 状态，0：无效，1：有效  
     * column{status},jdbcType{TINYINT}
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户id  
     * column{userid},jdbcType{BIGINT}
     */
    public Long getUserid() {
        return userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * 用户来源，1：QQ ， 2：SINA  
     * column{userfrom},jdbcType{TINYINT}
     */
    public Byte getUserfrom() {
        return userfrom;
    }

    public void setUserfrom(Byte userfrom) {
        this.userfrom = userfrom;
    }

    /**
     * 第三方平台的id  
     * column{openid},jdbcType{VARCHAR}
     */
    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * 关联时间  
     * column{createtime},jdbcType{TIMESTAMP}
     */
    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * 状态，0：无效，1：有效  
     * column{status},jdbcType{TINYINT}
     */
    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }
}