package com.zf.live.dao.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{userprops}
 * by is_zhoufeng@163.com 2014-12-15 17:32:50
 */
public class Userprops implements Serializable {
    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 用户id  
     * column{userid},jdbcType{BIGINT}
     */
    private Long userid;

    /**
     * 物品类型,1：VIP ， 2：靓号  
     * column{propstype},jdbcType{TINYINT}
     */
    private Byte propstype;

    /**
     * 物品名称  
     * column{propsname},jdbcType{VARCHAR}
     */
    private String propsname;

    /**
     * 失效时间  
     * column{expirationtime},jdbcType{TIMESTAMP}
     */
    private Date expirationtime;

    /**
     * 创建时间  
     * column{createtime},jdbcType{TIMESTAMP}
     */
    private Date createtime;

    /**
     * 状态  
     * column{status},jdbcType{TINYINT}
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userprops
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户id  
     * column{userid},jdbcType{BIGINT}
     */
    public Long getUserid() {
        return userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * 物品类型,1：VIP ， 2：靓号  
     * column{propstype},jdbcType{TINYINT}
     */
    public Byte getPropstype() {
        return propstype;
    }

    public void setPropstype(Byte propstype) {
        this.propstype = propstype;
    }

    /**
     * 物品名称  
     * column{propsname},jdbcType{VARCHAR}
     */
    public String getPropsname() {
        return propsname;
    }

    public void setPropsname(String propsname) {
        this.propsname = propsname;
    }

    /**
     * 失效时间  
     * column{expirationtime},jdbcType{TIMESTAMP}
     */
    public Date getExpirationtime() {
        return expirationtime;
    }

    public void setExpirationtime(Date expirationtime) {
        this.expirationtime = expirationtime;
    }

    /**
     * 创建时间  
     * column{createtime},jdbcType{TIMESTAMP}
     */
    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * 状态  
     * column{status},jdbcType{TINYINT}
     */
    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }
}