package com.zf.live.dao.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{video_group}
 * by is_zhoufeng@163.com 2015-01-10 02:06:27
 */
public class VideoGroup implements Serializable {
    /**
     * 视频来源，1：优酷  
     * column{id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     *   
     * column{videofrom},jdbcType{TINYINT}
     */
    private Byte videofrom;

    /**
     * 视频来源网站ID  
     * column{fromid},jdbcType{VARCHAR}
     */
    private String fromid;

    /**
     *   
     * column{group_name},jdbcType{VARCHAR}
     */
    private String groupName;

    /**
     * 截图  
     * column{thumbnail},jdbcType{VARCHAR}
     */
    private String thumbnail;

    /**
     * 视频数量  
     * column{video_count},jdbcType{INTEGER}
     */
    private Integer videoCount;

    /**
     * 第三方观看次数  
     * column{third_view_count},jdbcType{BIGINT}
     */
    private Long thirdViewCount;

    /**
     * 本平台视频播放次数  
     * column{view_count},jdbcType{BIGINT}
     */
    private Long viewCount;

    /**
     * 发布时间  
     * column{published},jdbcType{TIMESTAMP}
     */
    private Date published;

    /**
     * 分类  
     * column{category},jdbcType{VARCHAR}
     */
    private String category;

    /**
     * 标位  
     * column{flag},jdbcType{INTEGER}
     */
    private Integer flag;

    /**
     * 创建时间  
     * column{createtime},jdbcType{DATE}
     */
    private Date createtime;

    /**
     * 视频描述  
     * column{description},jdbcType{LONGVARCHAR}
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_group
     *
     * @mbggenerated Sat Jan 10 02:06:27 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * 视频来源，1：优酷  
     * column{id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     *   
     * column{videofrom},jdbcType{TINYINT}
     */
    public Byte getVideofrom() {
        return videofrom;
    }

    public void setVideofrom(Byte videofrom) {
        this.videofrom = videofrom;
    }

    /**
     * 视频来源网站ID  
     * column{fromid},jdbcType{VARCHAR}
     */
    public String getFromid() {
        return fromid;
    }

    public void setFromid(String fromid) {
        this.fromid = fromid;
    }

    /**
     *   
     * column{group_name},jdbcType{VARCHAR}
     */
    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * 截图  
     * column{thumbnail},jdbcType{VARCHAR}
     */
    public String getThumbnail() {
        return thumbnail;
    }

    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    /**
     * 视频数量  
     * column{video_count},jdbcType{INTEGER}
     */
    public Integer getVideoCount() {
        return videoCount;
    }

    public void setVideoCount(Integer videoCount) {
        this.videoCount = videoCount;
    }

    /**
     * 第三方观看次数  
     * column{third_view_count},jdbcType{BIGINT}
     */
    public Long getThirdViewCount() {
        return thirdViewCount;
    }

    public void setThirdViewCount(Long thirdViewCount) {
        this.thirdViewCount = thirdViewCount;
    }

    /**
     * 本平台视频播放次数  
     * column{view_count},jdbcType{BIGINT}
     */
    public Long getViewCount() {
        return viewCount;
    }

    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * 发布时间  
     * column{published},jdbcType{TIMESTAMP}
     */
    public Date getPublished() {
        return published;
    }

    public void setPublished(Date published) {
        this.published = published;
    }

    /**
     * 分类  
     * column{category},jdbcType{VARCHAR}
     */
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * 标位  
     * column{flag},jdbcType{INTEGER}
     */
    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * 创建时间  
     * column{createtime},jdbcType{DATE}
     */
    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * 视频描述  
     * column{description},jdbcType{LONGVARCHAR}
     */
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}