package com.zf.live.dao.pojo;

import java.io.Serializable;

/**
 * tableName{video_detail}
 * by is_zhoufeng@163.com 2015-01-05 00:14:43
 */
public class VideoDetail implements Serializable {
    /**
     * 对应video_id  
     * column{id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 视频时长  
     * column{duration},jdbcType{VARCHAR}
     */
    private String duration;

    /**
     * 视频播放链接  
     * column{link},jdbcType{VARCHAR}
     */
    private String link;

    /**
     * 视频大图  
     * column{bigthumbnail},jdbcType{VARCHAR}
     */
    private String bigthumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_detail
     *
     * @mbggenerated Mon Jan 05 00:14:43 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * 对应video_id  
     * column{id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 视频时长  
     * column{duration},jdbcType{VARCHAR}
     */
    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * 视频播放链接  
     * column{link},jdbcType{VARCHAR}
     */
    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    /**
     * 视频大图  
     * column{bigthumbnail},jdbcType{VARCHAR}
     */
    public String getBigthumbnail() {
        return bigthumbnail;
    }

    public void setBigthumbnail(String bigthumbnail) {
        this.bigthumbnail = bigthumbnail;
    }
}