package com.zf.live.dao.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{video}
 * by is_zhoufeng@163.com 2014-12-15 17:32:50
 */
public class Video implements Serializable {
    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 视频来源，1：优酷  
     * column{from},jdbcType{TINYINT}
     */
    private Byte from;

    /**
     * 视频来源网站ID  
     * column{fromid},jdbcType{VARCHAR}
     */
    private String fromid;

    /**
     * 视频名称  
     * column{videoname},jdbcType{VARCHAR}
     */
    private String videoname;

    /**
     * 视频图片  
     * column{videoimg},jdbcType{VARCHAR}
     */
    private String videoimg;

    /**
     * 视频时长（秒数）  
     * column{videolength},jdbcType{BIGINT}
     */
    private Long videolength;

    /**
     * 视频被赞次数  
     * column{praise},jdbcType{BIGINT}
     */
    private Long praise;

    /**
     * 扩展标位  
     * column{flag},jdbcType{INTEGER}
     */
    private Integer flag;

    /**
     * 创建时间  
     * column{createtime},jdbcType{TIMESTAMP}
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 视频来源，1：优酷  
     * column{from},jdbcType{TINYINT}
     */
    public Byte getFrom() {
        return from;
    }

    public void setFrom(Byte from) {
        this.from = from;
    }

    /**
     * 视频来源网站ID  
     * column{fromid},jdbcType{VARCHAR}
     */
    public String getFromid() {
        return fromid;
    }

    public void setFromid(String fromid) {
        this.fromid = fromid;
    }

    /**
     * 视频名称  
     * column{videoname},jdbcType{VARCHAR}
     */
    public String getVideoname() {
        return videoname;
    }

    public void setVideoname(String videoname) {
        this.videoname = videoname;
    }

    /**
     * 视频图片  
     * column{videoimg},jdbcType{VARCHAR}
     */
    public String getVideoimg() {
        return videoimg;
    }

    public void setVideoimg(String videoimg) {
        this.videoimg = videoimg;
    }

    /**
     * 视频时长（秒数）  
     * column{videolength},jdbcType{BIGINT}
     */
    public Long getVideolength() {
        return videolength;
    }

    public void setVideolength(Long videolength) {
        this.videolength = videolength;
    }

    /**
     * 视频被赞次数  
     * column{praise},jdbcType{BIGINT}
     */
    public Long getPraise() {
        return praise;
    }

    public void setPraise(Long praise) {
        this.praise = praise;
    }

    /**
     * 扩展标位  
     * column{flag},jdbcType{INTEGER}
     */
    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * 创建时间  
     * column{createtime},jdbcType{TIMESTAMP}
     */
    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}