package com.zf.live.dao.mapper;

import com.zf.live.dao.pojo.AudienceCount;
import com.zf.live.dao.pojo.AudienceCountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AudienceCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    int countByExample(AudienceCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    int deleteByExample(AudienceCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    int deleteByPrimaryKey(String vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    int insert(AudienceCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    int insertSelective(AudienceCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    List<AudienceCount> selectByExample(AudienceCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    AudienceCount selectByPrimaryKey(String vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") AudienceCount record, @Param("example") AudienceCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    int updateByExample(@Param("record") AudienceCount record, @Param("example") AudienceCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    int updateByPrimaryKeySelective(AudienceCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    int updateByPrimaryKey(AudienceCount record);
}