package com.zf.live.dao.mapper;

import com.zf.live.dao.pojo.LocalVideo;
import com.zf.live.dao.pojo.LocalVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocalVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int countByExample(LocalVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int deleteByExample(LocalVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int insert(LocalVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int insertSelective(LocalVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    List<LocalVideo> selectByExampleWithBLOBs(LocalVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    List<LocalVideo> selectByExample(LocalVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    LocalVideo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") LocalVideo record, @Param("example") LocalVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") LocalVideo record, @Param("example") LocalVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByExample(@Param("record") LocalVideo record, @Param("example") LocalVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByPrimaryKeySelective(LocalVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(LocalVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_video
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByPrimaryKey(LocalVideo record);
}