package com.zf.live.dao.mapper;

import com.zf.live.dao.pojo.Lvuser;
import com.zf.live.dao.pojo.LvuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LvuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuser
     *
     * @mbggenerated Thu Jan 01 16:54:31 CST 2015
     */
    int countByExample(LvuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuser
     *
     * @mbggenerated Thu Jan 01 16:54:31 CST 2015
     */
    int deleteByExample(LvuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuser
     *
     * @mbggenerated Thu Jan 01 16:54:31 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuser
     *
     * @mbggenerated Thu Jan 01 16:54:31 CST 2015
     */
    int insert(Lvuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuser
     *
     * @mbggenerated Thu Jan 01 16:54:31 CST 2015
     */
    int insertSelective(Lvuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuser
     *
     * @mbggenerated Thu Jan 01 16:54:31 CST 2015
     */
    List<Lvuser> selectByExample(LvuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuser
     *
     * @mbggenerated Thu Jan 01 16:54:31 CST 2015
     */
    Lvuser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuser
     *
     * @mbggenerated Thu Jan 01 16:54:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") Lvuser record, @Param("example") LvuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuser
     *
     * @mbggenerated Thu Jan 01 16:54:31 CST 2015
     */
    int updateByExample(@Param("record") Lvuser record, @Param("example") LvuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuser
     *
     * @mbggenerated Thu Jan 01 16:54:31 CST 2015
     */
    int updateByPrimaryKeySelective(Lvuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuser
     *
     * @mbggenerated Thu Jan 01 16:54:31 CST 2015
     */
    int updateByPrimaryKey(Lvuser record);
}