package com.zf.live.dao.mapper;

import com.zf.live.dao.pojo.Lvuserinfo;
import com.zf.live.dao.pojo.LvuserinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LvuserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuserinfo
     *
     * @mbggenerated Thu Jan 01 20:38:08 CST 2015
     */
    int countByExample(LvuserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuserinfo
     *
     * @mbggenerated Thu Jan 01 20:38:08 CST 2015
     */
    int deleteByExample(LvuserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuserinfo
     *
     * @mbggenerated Thu Jan 01 20:38:08 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuserinfo
     *
     * @mbggenerated Thu Jan 01 20:38:08 CST 2015
     */
    int insert(Lvuserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuserinfo
     *
     * @mbggenerated Thu Jan 01 20:38:08 CST 2015
     */
    int insertSelective(Lvuserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuserinfo
     *
     * @mbggenerated Thu Jan 01 20:38:08 CST 2015
     */
    List<Lvuserinfo> selectByExample(LvuserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuserinfo
     *
     * @mbggenerated Thu Jan 01 20:38:08 CST 2015
     */
    Lvuserinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuserinfo
     *
     * @mbggenerated Thu Jan 01 20:38:08 CST 2015
     */
    int updateByExampleSelective(@Param("record") Lvuserinfo record, @Param("example") LvuserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuserinfo
     *
     * @mbggenerated Thu Jan 01 20:38:08 CST 2015
     */
    int updateByExample(@Param("record") Lvuserinfo record, @Param("example") LvuserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuserinfo
     *
     * @mbggenerated Thu Jan 01 20:38:08 CST 2015
     */
    int updateByPrimaryKeySelective(Lvuserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lvuserinfo
     *
     * @mbggenerated Thu Jan 01 20:38:08 CST 2015
     */
    int updateByPrimaryKey(Lvuserinfo record);
}