package com.zf.live.dao.mapper;

import com.zf.live.dao.pojo.Praiserecored;
import com.zf.live.dao.pojo.PraiserecoredExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PraiserecoredMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praiserecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    int countByExample(PraiserecoredExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praiserecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    int deleteByExample(PraiserecoredExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praiserecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praiserecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    int insert(Praiserecored record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praiserecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    int insertSelective(Praiserecored record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praiserecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    List<Praiserecored> selectByExample(PraiserecoredExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praiserecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    Praiserecored selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praiserecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    int updateByExampleSelective(@Param("record") Praiserecored record, @Param("example") PraiserecoredExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praiserecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    int updateByExample(@Param("record") Praiserecored record, @Param("example") PraiserecoredExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praiserecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    int updateByPrimaryKeySelective(Praiserecored record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praiserecored
     *
     * @mbggenerated Mon Dec 15 17:32:50 CST 2014
     */
    int updateByPrimaryKey(Praiserecored record);
}