package com.zf.live.dao.mapper;

import com.zf.live.dao.pojo.Thirduser;
import com.zf.live.dao.pojo.ThirduserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThirduserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    int countByExample(ThirduserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    int deleteByExample(ThirduserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    int insert(Thirduser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    int insertSelective(Thirduser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    List<Thirduser> selectByExample(ThirduserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    Thirduser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") Thirduser record, @Param("example") ThirduserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    int updateByExample(@Param("record") Thirduser record, @Param("example") ThirduserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    int updateByPrimaryKeySelective(Thirduser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduser
     *
     * @mbggenerated Thu Jan 01 16:38:01 CST 2015
     */
    int updateByPrimaryKey(Thirduser record);
}