package com.zf.live.dao.mapper;

import com.zf.live.dao.pojo.VideoDetail;
import com.zf.live.dao.pojo.VideoDetailExample;
import com.zf.live.dao.pojo.VideoDetailWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int countByExample(VideoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int deleteByExample(VideoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int insert(VideoDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int insertSelective(VideoDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    List<VideoDetailWithBLOBs> selectByExampleWithBLOBs(VideoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    List<VideoDetail> selectByExample(VideoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    VideoDetailWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") VideoDetailWithBLOBs record, @Param("example") VideoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") VideoDetailWithBLOBs record, @Param("example") VideoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByExample(@Param("record") VideoDetail record, @Param("example") VideoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByPrimaryKeySelective(VideoDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(VideoDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_detail
     *
     * @mbggenerated Thu Feb 05 22:36:26 CST 2015
     */
    int updateByPrimaryKey(VideoDetail record);
}