package com.zf.live.dao.pojo;

import com.zf.live.dao.vo.Page;
import java.util.ArrayList;
import java.util.List;

public class AudienceCountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public AudienceCountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVidIsNull() {
            addCriterion("vid is null");
            return (Criteria) this;
        }

        public Criteria andVidIsNotNull() {
            addCriterion("vid is not null");
            return (Criteria) this;
        }

        public Criteria andVidEqualTo(String value) {
            addCriterion("vid =", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotEqualTo(String value) {
            addCriterion("vid <>", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThan(String value) {
            addCriterion("vid >", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThanOrEqualTo(String value) {
            addCriterion("vid >=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThan(String value) {
            addCriterion("vid <", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThanOrEqualTo(String value) {
            addCriterion("vid <=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLike(String value) {
            addCriterion("vid like", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotLike(String value) {
            addCriterion("vid not like", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidIn(List<String> values) {
            addCriterion("vid in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotIn(List<String> values) {
            addCriterion("vid not in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidBetween(String value1, String value2) {
            addCriterion("vid between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotBetween(String value1, String value2) {
            addCriterion("vid not between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryIsNull() {
            addCriterion("video_category is null");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryIsNotNull() {
            addCriterion("video_category is not null");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryEqualTo(String value) {
            addCriterion("video_category =", value, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryNotEqualTo(String value) {
            addCriterion("video_category <>", value, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryGreaterThan(String value) {
            addCriterion("video_category >", value, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("video_category >=", value, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryLessThan(String value) {
            addCriterion("video_category <", value, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryLessThanOrEqualTo(String value) {
            addCriterion("video_category <=", value, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryLike(String value) {
            addCriterion("video_category like", value, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryNotLike(String value) {
            addCriterion("video_category not like", value, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryIn(List<String> values) {
            addCriterion("video_category in", values, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryNotIn(List<String> values) {
            addCriterion("video_category not in", values, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryBetween(String value1, String value2) {
            addCriterion("video_category between", value1, value2, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andVideoCategoryNotBetween(String value1, String value2) {
            addCriterion("video_category not between", value1, value2, "videoCategory");
            return (Criteria) this;
        }

        public Criteria andAudienceCountIsNull() {
            addCriterion("audience_count is null");
            return (Criteria) this;
        }

        public Criteria andAudienceCountIsNotNull() {
            addCriterion("audience_count is not null");
            return (Criteria) this;
        }

        public Criteria andAudienceCountEqualTo(Integer value) {
            addCriterion("audience_count =", value, "audienceCount");
            return (Criteria) this;
        }

        public Criteria andAudienceCountNotEqualTo(Integer value) {
            addCriterion("audience_count <>", value, "audienceCount");
            return (Criteria) this;
        }

        public Criteria andAudienceCountGreaterThan(Integer value) {
            addCriterion("audience_count >", value, "audienceCount");
            return (Criteria) this;
        }

        public Criteria andAudienceCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("audience_count >=", value, "audienceCount");
            return (Criteria) this;
        }

        public Criteria andAudienceCountLessThan(Integer value) {
            addCriterion("audience_count <", value, "audienceCount");
            return (Criteria) this;
        }

        public Criteria andAudienceCountLessThanOrEqualTo(Integer value) {
            addCriterion("audience_count <=", value, "audienceCount");
            return (Criteria) this;
        }

        public Criteria andAudienceCountIn(List<Integer> values) {
            addCriterion("audience_count in", values, "audienceCount");
            return (Criteria) this;
        }

        public Criteria andAudienceCountNotIn(List<Integer> values) {
            addCriterion("audience_count not in", values, "audienceCount");
            return (Criteria) this;
        }

        public Criteria andAudienceCountBetween(Integer value1, Integer value2) {
            addCriterion("audience_count between", value1, value2, "audienceCount");
            return (Criteria) this;
        }

        public Criteria andAudienceCountNotBetween(Integer value1, Integer value2) {
            addCriterion("audience_count not between", value1, value2, "audienceCount");
            return (Criteria) this;
        }

        public Criteria andTouristCountIsNull() {
            addCriterion("tourist_count is null");
            return (Criteria) this;
        }

        public Criteria andTouristCountIsNotNull() {
            addCriterion("tourist_count is not null");
            return (Criteria) this;
        }

        public Criteria andTouristCountEqualTo(Integer value) {
            addCriterion("tourist_count =", value, "touristCount");
            return (Criteria) this;
        }

        public Criteria andTouristCountNotEqualTo(Integer value) {
            addCriterion("tourist_count <>", value, "touristCount");
            return (Criteria) this;
        }

        public Criteria andTouristCountGreaterThan(Integer value) {
            addCriterion("tourist_count >", value, "touristCount");
            return (Criteria) this;
        }

        public Criteria andTouristCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("tourist_count >=", value, "touristCount");
            return (Criteria) this;
        }

        public Criteria andTouristCountLessThan(Integer value) {
            addCriterion("tourist_count <", value, "touristCount");
            return (Criteria) this;
        }

        public Criteria andTouristCountLessThanOrEqualTo(Integer value) {
            addCriterion("tourist_count <=", value, "touristCount");
            return (Criteria) this;
        }

        public Criteria andTouristCountIn(List<Integer> values) {
            addCriterion("tourist_count in", values, "touristCount");
            return (Criteria) this;
        }

        public Criteria andTouristCountNotIn(List<Integer> values) {
            addCriterion("tourist_count not in", values, "touristCount");
            return (Criteria) this;
        }

        public Criteria andTouristCountBetween(Integer value1, Integer value2) {
            addCriterion("tourist_count between", value1, value2, "touristCount");
            return (Criteria) this;
        }

        public Criteria andTouristCountNotBetween(Integer value1, Integer value2) {
            addCriterion("tourist_count not between", value1, value2, "touristCount");
            return (Criteria) this;
        }

        public Criteria andUserCountIsNull() {
            addCriterion("user_count is null");
            return (Criteria) this;
        }

        public Criteria andUserCountIsNotNull() {
            addCriterion("user_count is not null");
            return (Criteria) this;
        }

        public Criteria andUserCountEqualTo(Integer value) {
            addCriterion("user_count =", value, "userCount");
            return (Criteria) this;
        }

        public Criteria andUserCountNotEqualTo(Integer value) {
            addCriterion("user_count <>", value, "userCount");
            return (Criteria) this;
        }

        public Criteria andUserCountGreaterThan(Integer value) {
            addCriterion("user_count >", value, "userCount");
            return (Criteria) this;
        }

        public Criteria andUserCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_count >=", value, "userCount");
            return (Criteria) this;
        }

        public Criteria andUserCountLessThan(Integer value) {
            addCriterion("user_count <", value, "userCount");
            return (Criteria) this;
        }

        public Criteria andUserCountLessThanOrEqualTo(Integer value) {
            addCriterion("user_count <=", value, "userCount");
            return (Criteria) this;
        }

        public Criteria andUserCountIn(List<Integer> values) {
            addCriterion("user_count in", values, "userCount");
            return (Criteria) this;
        }

        public Criteria andUserCountNotIn(List<Integer> values) {
            addCriterion("user_count not in", values, "userCount");
            return (Criteria) this;
        }

        public Criteria andUserCountBetween(Integer value1, Integer value2) {
            addCriterion("user_count between", value1, value2, "userCount");
            return (Criteria) this;
        }

        public Criteria andUserCountNotBetween(Integer value1, Integer value2) {
            addCriterion("user_count not between", value1, value2, "userCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table audience_count
     *
     * @mbggenerated do_not_delete_during_merge Sun Feb 08 22:22:39 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table audience_count
     *
     * @mbggenerated Sun Feb 08 22:22:39 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}